# Generated by Django 2.0.5 on 2018-05-28 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polity', '0011_auto_20180527_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('eco_bonus', models.FloatField(default=0)),
                ('loy_bonus', models.FloatField(default=0)),
                ('sta_bonus', models.FloatField(default=0)),
                ('fam_bonus', models.FloatField(default=0)),
                ('inf_bonus', models.FloatField(default=0)),
                ('cor_bonus', models.FloatField(default=0)),
                ('cri_bonus', models.FloatField(default=0)),
                ('law_bonus', models.FloatField(default=0)),
                ('lor_bonus', models.FloatField(default=0)),
                ('pro_bonus', models.FloatField(default=0)),
                ('soc_bonus', models.FloatField(default=0)),
                ('def_bonus', models.FloatField(default=0)),
                ('con_bonus', models.FloatField(default=0)),
                ('inc_bonus', models.FloatField(default=0)),
                ('unr_bonus', models.FloatField(default=0)),
                ('polity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', related_query_name='event', to='polity.Polity')),
            ],
        ),
    ]
