# Generated by Django 2.0.5 on 2018-05-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='con_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='cor_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='cri_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='def_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='eco_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='fam_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='inc_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='inf_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='law_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lor_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='loy_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='pro_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='soc_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='sta_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unr_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
