# Generated by Django 2.0.5 on 2018-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='cor_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='cri_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='eco_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='fam_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='inf_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='law_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='lor_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='loy_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='pro_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='soc_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='sta_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
