# Generated by Django 2.0.5 on 2018-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0002_auto_20180601_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction', related_query_name='faction', to='factions.Type'),
        ),
    ]
