# Generated by Django 2.0.5 on 2018-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0003_auto_20180607_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
