# Generated by Django 2.0.5 on 2018-05-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0011_auto_20180527_1651'),
        ('diplomacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaticRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiplomaticRelation', related_query_name='DiplomaticRelation', to='diplomacy.Attitude')),
                ('polity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiplomaticRelation', related_query_name='DiplomaticRelation', to='polity.Polity')),
            ],
        ),
        migrations.RemoveField(
            model_name='diplomaticrelations',
            name='attitude',
        ),
        migrations.RemoveField(
            model_name='diplomaticrelations',
            name='polity',
        ),
        migrations.DeleteModel(
            name='DiplomaticRelations',
        ),
    ]
