# Generated by Django 2.0.5 on 2018-05-28 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0002_auto_20180527_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticrelation',
            name='attitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiplomaticRelation', related_query_name='DiplomaticRelation', to='diplomacy.Attitude'),
        ),
    ]
