# Generated by Django 2.0.5 on 2018-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0003_auto_20180527_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomaticrelation',
            name='polity',
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='name',
            field=models.CharField(default='something', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
