# Generated by Django 2.0.5 on 2018-05-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0005_auto_20180527_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='step',
            field=models.IntegerField(unique=True),
        ),
    ]
