# Generated by Django 2.0.5 on 2018-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0006_auto_20180527_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balanced', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='economy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='stability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='treaties',
            field=models.ManyToManyField(blank=True, related_name='diplomatic_relation', related_query_name='diplomatic_relation', to='diplomacy.Treaty'),
        ),
    ]
