# Generated by Django 2.0.5 on 2018-05-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0007_auto_20180527_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treaty',
            name='balanced',
        ),
        migrations.AddField(
            model_name='treaty',
            name='eco_mult',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='treaty',
            name='sta_mult',
            field=models.FloatField(default=0),
        ),
    ]
