# Generated by Django 2.0.5 on 2018-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0010_auto_20180527_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticrelation',
            name='target',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
