# Generated by Django 2.0.5 on 2018-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0011_auto_20180527_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticrelation',
            name='attitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomaticRelation', related_query_name='DiplomaticRelation', to='diplomacy.Attitude'),
        ),
    ]
