# Generated by Django 2.0.5 on 2018-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_polity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxEdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('revenue_divisor', models.IntegerField()),
                ('eco_bonus', models.IntegerField()),
                ('loy_bonus', models.IntegerField()),
            ],
        ),
    ]
