# Generated by Django 2.0.5 on 2018-05-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taxedict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxedict',
            name='revenue_divisor',
            field=models.FloatField(),
        ),
    ]
