# Generated by Django 2.0.5 on 2018-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promotionedict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionedict',
            name='con_dice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
