# Generated by Django 2.0.5 on 2018-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180527_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayEdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eco_bonus', models.IntegerField()),
                ('loy_bonus', models.IntegerField()),
                ('con_bonus', models.IntegerField()),
                ('con_dice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
