# Generated by Django 2.0.5 on 2018-05-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_holidayedict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayedict',
            old_name='name',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='promotionedict',
            old_name='name',
            new_name='attitude',
        ),
        migrations.RenameField(
            model_name='taxedict',
            old_name='name',
            new_name='tax_level',
        ),
    ]
