# Generated by Django 2.0.5 on 2018-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180527_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('militarism', models.CharField(max_length=100)),
                ('manpower_mult', models.FloatField()),
                ('elites_mult', models.IntegerField()),
                ('fam_bonus', models.IntegerField()),
                ('inf_bonus', models.IntegerField()),
                ('def_bonus', models.IntegerField()),
                ('eco_bonus', models.IntegerField()),
                ('soc_bonus', models.IntegerField()),
            ],
        ),
    ]
