# Generated by Django 2.0.5 on 2018-05-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_magicalenhancement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicalEnhancement',
        ),
    ]
