# Generated by Django 2.0.5 on 2018-05-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_magicalenhancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentedict',
            name='armed_forces_mult',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
