# Generated by Django 2.0.5 on 2018-05-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_recruitmentedict_armed_forces_mult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentedict',
            name='armed_forces_mult',
        ),
    ]
