# Generated by Django 2.0.5 on 2018-06-01 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polity', '0012_auto_20180530_0937'),
        ('settlements', '0028_building_free_endowment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=1)),
                ('investment', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('polity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_route', related_query_name='trade_route', to='polity.Polity')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_route', related_query_name='trade_route', to='settlements.Settlement')),
                ('success_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_route', related_query_name='trade_route', to='trade.SuccessLevel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_route', related_query_name='trade_route', to='trade.RouteType')),
            ],
        ),
    ]
