# Generated by Django 2.0.5 on 2018-06-01 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180531_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderoute',
            name='success_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_route', related_query_name='trade_route', to='trade.SuccessLevel'),
        ),
    ]
