# Generated by Django 2.0.5 on 2018-06-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_successlevel_unrest_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successlevel',
            name='treasury_increment',
        ),
    ]
