# Generated by Django 2.0.5 on 2018-06-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_remove_successlevel_treasury_increment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successlevel',
            old_name='fam_increment',
            new_name='fame_increment',
        ),
    ]
