# Generated by Django 2.0.5 on 2018-05-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='features',
            field=models.ManyToManyField(related_name='territory', related_query_name='territories', to='territory.Feature'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='improvements',
            field=models.ManyToManyField(related_name='territory', related_query_name='territories', to='territory.Improvement'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territories', to='territory.Type'),
        ),
    ]
