# Generated by Django 2.0.5 on 2018-05-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0003_territory_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='exp_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='type',
            name='farm_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='type',
            name='prep_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='type',
            name='prep_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='type',
            name='road_cost',
            field=models.IntegerField(default=1),
        ),
    ]
