# Generated by Django 2.0.5 on 2018-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0004_auto_20180525_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
