# Generated by Django 2.0.5 on 2018-05-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0007_auto_20180525_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvement',
            name='construction_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='improvement',
            name='cost_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
