# Generated by Django 2.0.5 on 2018-05-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0008_auto_20180525_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvement',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
