# Generated by Django 2.0.5 on 2018-05-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0009_improvement_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvement',
            name='eco_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='loy_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='sta_bonus',
            field=models.FloatField(default=0),
        ),
    ]
