# Generated by Django 2.0.5 on 2018-05-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0010_auto_20180525_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='con_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='dan_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='def_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='eco_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='inc_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='loy_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='pop_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='sta_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='unr_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
