# Generated by Django 2.0.5 on 2018-05-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0002_auto_20180525_2237'),
        ('territory', '0011_auto_20180525_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='polity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territory', to='polity.Polity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='territory',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='territory', related_query_name='territory', to='territory.Feature'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='improvements',
            field=models.ManyToManyField(blank=True, related_name='territory', related_query_name='territory', to='territory.Improvement'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territory', to='territory.Type'),
        ),
    ]
