# Generated by Django 2.0.5 on 2018-05-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0013_enhancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='enhancements',
            field=models.ManyToManyField(blank=True, related_name='territory', related_query_name='territory', to='territory.Enhancement'),
        ),
    ]
