# Generated by Django 2.0.5 on 2018-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0014_territory_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territory',
            name='enhancements',
        ),
        migrations.AddField(
            model_name='improvement',
            name='dan_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='improvement',
            name='fam_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='improvement',
            name='inf_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Enhancement',
        ),
    ]
