# Generated by Django 2.0.5 on 2018-06-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0016_auto_20180531_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='resource_type',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
