# Generated by Django 2.0.5 on 2018-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0017_auto_20180531_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
