# Generated by Django 2.0.5 on 2018-06-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0020_auto_20180603_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territory', to='territory.Map'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='polity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territory', to='polity.Polity'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territory', to='territory.Type'),
        ),
    ]
