# Generated by Django 2.0.5 on 2018-06-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0021_auto_20180603_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='polity',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='territory', related_query_name='territory', to='polity.Polity'),
        ),
    ]
