# Generated by Django 2.0.5 on 2018-06-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0022_auto_20180603_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
