# Generated by Django 2.0.5 on 2018-06-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0023_territory_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
