# Generated by Django 2.0.5 on 2018-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0024_territory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='polity',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory', related_query_name='territory', to='polity.Polity'),
        ),
    ]
