# Generated by Django 2.0.5 on 2018-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0025_auto_20180607_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
