# Generated by Django 2.0.5 on 2018-09-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0026_territory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='explored',
            field=models.BooleanField(default=False),
        ),
    ]
