# Generated by Django 2.0.5 on 2018-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0002_auto_20180525_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlignmentLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
    ]
