# Generated by Django 2.0.5 on 2018-05-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0003_alignmentge_alignmentlc_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='alignment_ge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='polity.AlignmentGE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='alignment_lc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='polity.AlignmentLC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='government',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='polity.Government'),
            preserve_default=False,
        ),
    ]
