# Generated by Django 2.0.5 on 2018-05-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0006_attributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='Attribute',
        ),
    ]
