# Generated by Django 2.0.5 on 2018-05-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0007_auto_20180527_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='ruler_attribute_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity_ruler_1', related_query_name='polity_ruler_1', to='polity.Attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='ruler_attribute_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity_ruler_2', related_query_name='polity_ruler_2', to='polity.Attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='ruler_attribute_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity_ruler_3', related_query_name='polity_ruler_3', to='polity.Attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='spymaster_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity_spymaster', related_query_name='polity_spymaster', to='polity.Attribute'),
            preserve_default=False,
        ),
    ]
