# Generated by Django 2.0.5 on 2018-05-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180527_1630'),
        ('polity', '0010_auto_20180527_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='holiday_edict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='core.HolidayEdict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='promotion_edict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='core.PromotionEdict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='recruitment_edict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='core.RecruitmentEdict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polity',
            name='tax_edict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polity', related_query_name='polity', to='core.TaxEdict'),
            preserve_default=False,
        ),
    ]
