# Generated by Django 2.0.5 on 2018-06-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_month'),
        ('polity', '0012_auto_20180530_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1480)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entry', related_query_name='log_entry', to='core.Month')),
                ('polity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entry', related_query_name='log_entry', to='polity.Polity')),
            ],
        ),
    ]
