# Generated by Django 2.0.5 on 2018-06-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0014_auto_20180601_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='polity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='log_entry', related_query_name='log_entry', to='polity.Polity'),
        ),
    ]
