# Generated by Django 2.0.5 on 2018-05-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='noble_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.NobleRank'),
        ),
    ]
