# Generated by Django 2.0.5 on 2018-05-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180524_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='awards',
        ),
        migrations.AddField(
            model_name='award',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', related_query_name='award', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='award',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noblerank',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noblerank',
            name='honorific',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='cha',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='con',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='dex',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='int',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='noble_rank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.NobleRank'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='str',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='wis',
            field=models.IntegerField(default=10),
        ),
    ]
