# Generated by Django 2.0.5 on 2018-05-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180524_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', related_query_name='person', to='people.Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='noble_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', related_query_name='person', to='people.NobleRank'),
        ),
    ]
