# Generated by Django 2.0.5 on 2018-05-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180524_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noblerank',
            old_name='name',
            new_name='female_title',
        ),
        migrations.RenameField(
            model_name='noblerank',
            old_name='equivalence',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='noblerank',
            name='honorific',
        ),
        migrations.AddField(
            model_name='noblerank',
            name='female_honorific',
            field=models.CharField(default='Temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noblerank',
            name='male_honorific',
            field=models.CharField(default='Temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noblerank',
            name='male_title',
            field=models.CharField(default='Temp', max_length=100),
            preserve_default=False,
        ),
    ]
