# Generated by Django 2.0.5 on 2018-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20180525_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='person', related_query_name='people', to='people.Award'),
        ),
    ]
