# Generated by Django 2.0.5 on 2018-05-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0011_auto_20180527_1651'),
        ('people', '0010_auto_20180526_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='polity',
        ),
        migrations.AddField(
            model_name='person',
            name='polity',
            field=models.ManyToManyField(related_name='person', related_query_name='person', to='polity.Polity'),
        ),
    ]
