# Generated by Django 2.0.5 on 2018-05-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20180527_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hit_dice',
            field=models.IntegerField(default=1),
        ),
    ]
