# Generated by Django 2.0.5 on 2018-05-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0017_boon'),
        ('people', '0013_person_hit_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='boons',
            field=models.ManyToManyField(blank=True, related_name='person', related_query_name='person', to='armed_forces.Boon'),
        ),
    ]
