# Generated by Django 2.0.5 on 2018-06-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_person_boons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
                ('leadership_bonus', models.IntegerField(default=0)),
                ('leadership_bonus_eco', models.IntegerField(default=0)),
                ('leadership_bonus_loy', models.IntegerField(default=0)),
                ('leadership_bonus_sta', models.IntegerField(default=0)),
                ('other_benefits', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', related_query_name='person', to='people.Advisor'),
        ),
    ]
