# Generated by Django 2.0.5 on 2018-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20180603_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', related_query_name='person', to='people.Advisor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', related_query_name='person', to='people.Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='leadership_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', related_query_name='person', to='people.LeadershipRole'),
        ),
        migrations.AlterField(
            model_name='person',
            name='noble_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', related_query_name='person', to='people.NobleRank'),
        ),
        migrations.AlterField(
            model_name='person',
            name='polity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', related_query_name='person', to='polity.Polity'),
        ),
    ]
