# Generated by Django 2.0.5 on 2018-05-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0003_auto_20180529_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='armedforce',
            name='soldier_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armed_force', related_query_name='armed_force', to='armed_forces.SoldierType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armedforce',
            name='unit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armed_force', related_query_name='armed_force', to='armed_forces.UnitType'),
            preserve_default=False,
        ),
    ]
