# Generated by Django 2.0.5 on 2018-05-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0005_auto_20180529_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='armedforce',
            name='custom_cr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armedforce',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='armedforce',
            name='hit_die',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='armedforce',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armed_force', related_query_name='armed_force', to='armed_forces.UnitType'),
        ),
        migrations.AlterField(
            model_name='armedforce',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armed_force', related_query_name='armed_force', to='armed_forces.SoldierType'),
        ),
    ]
