# Generated by Django 2.0.5 on 2018-05-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0006_auto_20180529_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldiertype',
            name='default_cr',
            field=models.FloatField(default=1),
        ),
    ]
