# Generated by Django 2.0.5 on 2018-05-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0007_auto_20180529_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armedforce',
            name='custom_cr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
