# Generated by Django 2.0.5 on 2018-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0008_auto_20180529_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='armedforce',
            name='morale',
            field=models.IntegerField(default=0),
        ),
    ]
