# Generated by Django 2.0.5 on 2018-05-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0009_armedforce_morale'),
    ]

    operations = [
        migrations.AddField(
            model_name='armedforce',
            name='speed',
            field=models.IntegerField(default=1),
        ),
    ]
