# Generated by Django 2.0.5 on 2018-05-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0011_armedforce_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='armedforce',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
