# Generated by Django 2.0.5 on 2018-05-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0026_building_enhancements'),
        ('armed_forces', '0013_auto_20180529_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='requirements',
        ),
        migrations.AddField(
            model_name='equipment',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='required_for_equipment', related_query_name='required_for_equipment', to='settlements.Building'),
        ),
    ]
