# Generated by Django 2.0.5 on 2018-05-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0014_auto_20180529_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='required_for_equipment', related_query_name='required_for_equipment', to='settlements.BuildingType'),
        ),
    ]
