# Generated by Django 2.0.5 on 2018-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0015_auto_20180529_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='armedforce',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='armed_force', related_query_name='armed_force', to='armed_forces.Equipment'),
        ),
    ]
