# Generated by Django 2.0.5 on 2018-05-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0016_armedforce_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
