# Generated by Django 2.0.5 on 2018-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0018_auto_20180529_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='armedforce',
            name='tactics_known',
            field=models.ManyToManyField(blank=True, related_name='armed_force', related_query_name='armed_force', to='armed_forces.Tactic'),
        ),
    ]
