# Generated by Django 2.0.5 on 2018-05-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0019_auto_20180529_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armedforce',
            name='tactics_known',
            field=models.ManyToManyField(blank=True, default=20, related_name='armed_force', related_query_name='armed_force', to='armed_forces.Tactic'),
        ),
    ]
