# Generated by Django 2.0.5 on 2018-05-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0020_auto_20180529_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armedforce',
            name='polity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armed_force', related_query_name='armed_force', to='polity.Polity'),
        ),
    ]
