# Generated by Django 2.0.5 on 2018-05-30 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0022_casualty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualty',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty', related_query_name='casualty', to='armed_forces.ArmedForce'),
        ),
    ]
