# Generated by Django 2.0.5 on 2018-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armed_forces', '0023_auto_20180529_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armedforce',
            name='commander',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armed_force', related_query_name='armed_force', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='armedforce',
            name='polity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armed_force', related_query_name='armed_force', to='polity.Polity'),
        ),
        migrations.AlterField(
            model_name='armedforce',
            name='size',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armed_force', related_query_name='armed_force', to='armed_forces.UnitType'),
        ),
        migrations.AlterField(
            model_name='armedforce',
            name='type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armed_force', related_query_name='armed_force', to='armed_forces.SoldierType'),
        ),
        migrations.AlterField(
            model_name='casualty',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casualty', related_query_name='casualty', to='armed_forces.ArmedForce'),
        ),
    ]
