# Generated by Django 2.0.5 on 2018-05-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('const_cost', models.IntegerField()),
                ('const_time', models.IntegerField()),
                ('lots', models.IntegerField(default=1)),
                ('pop_bonus', models.IntegerField(default=0)),
                ('eco_bonus', models.IntegerField(default=0)),
                ('loy_bonus', models.IntegerField(default=0)),
                ('sta_bonus', models.IntegerField(default=0)),
                ('fam_bonus', models.IntegerField(default=0)),
                ('inf_bonus', models.IntegerField(default=0)),
                ('cor_bonus', models.IntegerField(default=0)),
                ('cri_bonus', models.IntegerField(default=0)),
                ('law_bonus', models.IntegerField(default=0)),
                ('lor_bonus', models.IntegerField(default=0)),
                ('pro_bonus', models.IntegerField(default=0)),
                ('soc_bonus', models.IntegerField(default=0)),
                ('def_bonus', models.IntegerField(default=0)),
                ('con_bonus', models.IntegerField(default=0)),
                ('inc_bonus', models.IntegerField(default=0)),
                ('unr_bonus', models.IntegerField(default=0)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('discounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounted_from', related_query_name='discounted_from', to='settlements.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_lots', models.IntegerField()),
                ('con_bonus', models.IntegerField()),
                ('pop_mult', models.FloatField()),
                ('dan_mod', models.IntegerField()),
                ('att_mod', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='required_settlement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', related_query_name='building', to='settlements.Type'),
        ),
        migrations.AddField(
            model_name='building',
            name='upgrade_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_from', related_query_name='upgrade_from', to='settlements.Building'),
        ),
    ]
