# Generated by Django 2.0.5 on 2018-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0009_auto_20180528_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='magic_items',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
