# Generated by Django 2.0.5 on 2018-05-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0010_auto_20180528_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='building',
            name='upgrade_to',
        ),
    ]
