# Generated by Django 2.0.5 on 2018-05-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0011_auto_20180528_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='dan_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
