# Generated by Django 2.0.5 on 2018-05-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0012_auto_20180525_2302'),
        ('settlements', '0012_building_dan_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', related_query_name='settlement', to='territory.Territory')),
            ],
        ),
    ]
