# Generated by Django 2.0.5 on 2018-05-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0015_auto_20180528_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AddField(
            model_name='settlement',
            name='districts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', related_query_name='building', to='settlements.Settlement'),
        ),
        migrations.AddField(
            model_name='building',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', related_query_name='building', to='settlements.BuildingType'),
        ),
    ]
