# Generated by Django 2.0.5 on 2018-05-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0017_building_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingtype',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='buildingtype',
            name='upgrade_to',
        ),
    ]
