# Generated by Django 2.0.5 on 2018-05-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0019_remove_buildingtype_required_settlement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='_buildingtype_discounts_+', related_query_name='discounted_from', to='settlements.BuildingType'),
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='required_settlement_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_type', related_query_name='building_type', to='settlements.Type'),
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='upgrade_to',
            field=models.ManyToManyField(blank=True, related_name='_buildingtype_upgrade_to_+', related_query_name='upgrade_from', to='settlements.BuildingType'),
        ),
    ]
