# Generated by Django 2.0.5 on 2018-05-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0021_settlement_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingEnhancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pop_bonus', models.IntegerField(default=0)),
                ('dan_bonus', models.IntegerField(default=0)),
                ('eco_bonus', models.IntegerField(default=0)),
                ('loy_bonus', models.IntegerField(default=0)),
                ('sta_bonus', models.IntegerField(default=0)),
                ('fam_bonus', models.IntegerField(default=0)),
                ('inf_bonus', models.FloatField(default=0)),
                ('cor_bonus', models.IntegerField(default=0)),
                ('cri_bonus', models.IntegerField(default=0)),
                ('law_bonus', models.IntegerField(default=0)),
                ('lor_bonus', models.IntegerField(default=0)),
                ('pro_bonus', models.IntegerField(default=0)),
                ('soc_bonus', models.IntegerField(default=0)),
                ('def_bonus', models.IntegerField(default=0)),
                ('con_bonus', models.IntegerField(default=0)),
                ('inc_bonus', models.IntegerField(default=0)),
                ('unr_bonus', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement', related_query_name='enhancement', to='settlements.Building')),
            ],
        ),
    ]
