# Generated by Django 2.0.5 on 2018-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0022_buildingenhancement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingenhancement',
            name='building',
        ),
        migrations.AddField(
            model_name='buildingenhancement',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
