# Generated by Django 2.0.5 on 2018-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0023_auto_20180529_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingenhancement',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildingenhancement',
            name='inf_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
