# Generated by Django 2.0.5 on 2018-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0024_auto_20180529_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingenhancement',
            name='cost_per_lot',
            field=models.BooleanField(default=False),
        ),
    ]
