# Generated by Django 2.0.5 on 2018-05-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0025_buildingenhancement_cost_per_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='enhancements',
            field=models.ManyToManyField(blank=True, related_name='building', related_query_name='building', to='settlements.BuildingEnhancement'),
        ),
    ]
