# Generated by Django 2.0.5 on 2018-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0026_building_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='endowment',
            field=models.BooleanField(default=False),
        ),
    ]
