# Generated by Django 2.0.5 on 2018-06-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0028_building_free_endowment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='deity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', related_query_name='building', to='settlements.Deity'),
        ),
    ]
