# Generated by Django 2.0.5 on 2018-06-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0018_auto_20180531_2339'),
        ('settlements', '0029_auto_20180531_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stronghold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stronghold', related_query_name='stronghold', to='settlements.Settlement')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stronghold', related_query_name='stronghold', to='territory.Territory')),
            ],
        ),
    ]
