# Generated by Django 2.0.5 on 2018-06-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0015_auto_20180601_1403'),
        ('settlements', '0030_stronghold'),
    ]

    operations = [
        migrations.AddField(
            model_name='stronghold',
            name='polity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stronghold', related_query_name='stronghold', to='polity.Polity'),
        ),
    ]
