# Generated by Django 2.0.5 on 2018-06-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0032_auto_20180601_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='strongholdtype',
            name='construction_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strongholdtype',
            name='cost',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='strongholdtype',
            name='expansion_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strongholdtype',
            name='hirelings_skilled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strongholdtype',
            name='hirelings_unskilled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strongholdtype',
            name='upkeep',
            field=models.IntegerField(default=0),
        ),
    ]
