# Generated by Django 2.0.5 on 2018-06-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0033_auto_20180601_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='stronghold',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stronghold', related_query_name='stronghold', to='settlements.StrongholdType'),
            preserve_default=False,
        ),
    ]
