# Generated by Django 2.0.5 on 2018-06-01 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0034_stronghold_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slots', models.IntegerField(default=1)),
                ('cost', models.IntegerField()),
                ('construction_time', models.IntegerField(default=1)),
                ('benefit', models.TextField(blank=True)),
                ('stronghold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansion', related_query_name='expansion', to='settlements.Stronghold')),
            ],
        ),
    ]
