# Generated by Django 2.0.5 on 2018-06-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0035_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slots', models.IntegerField(default=1)),
                ('cost', models.IntegerField()),
                ('construction_time', models.IntegerField(default=1)),
                ('benefit', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='expansion',
            old_name='name',
            new_name='custom_name',
        ),
        migrations.RemoveField(
            model_name='expansion',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='expansion',
            name='construction_time',
        ),
        migrations.RemoveField(
            model_name='expansion',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='expansion',
            name='slots',
        ),
        migrations.AddField(
            model_name='expansion',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expansion', related_query_name='expansion', to='settlements.ExpansionType'),
            preserve_default=False,
        ),
    ]
