# Generated by Django 2.0.5 on 2018-06-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0036_auto_20180601_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansiontype',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
