# Generated by Django 2.0.5 on 2018-06-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0037_expansiontype_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
