# Generated by Django 2.0.5 on 2018-06-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0038_auto_20180601_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
