# Generated by Django 2.0.5 on 2018-06-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0040_auto_20180601_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansionfeature',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
