# Generated by Django 2.0.5 on 2018-06-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0041_expansionfeature_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansionfeature',
            name='reqs',
            field=models.TextField(blank=True),
        ),
    ]
