# Generated by Django 2.0.5 on 2018-06-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0042_expansionfeature_reqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansiontype',
            name='income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
