# Generated by Django 2.0.5 on 2018-06-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0045_auto_20180603_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.IntegerField()),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot', related_query_name='lot', to='settlements.Settlement')),
            ],
        ),
    ]
