# Generated by Django 2.0.5 on 2018-06-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0046_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', related_query_name='district', to='settlements.Settlement')),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='settlement',
        ),
        migrations.AddField(
            model_name='lot',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lot', related_query_name='lot', to='settlements.District'),
            preserve_default=False,
        ),
    ]
