# Generated by Django 2.0.5 on 2018-06-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0047_auto_20180607_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='districts',
        ),
    ]
