# Generated by Django 2.0.5 on 2018-06-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0048_remove_settlement_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot', related_query_name='lot', to='settlements.Building'),
        ),
        migrations.AlterField(
            model_name='building',
            name='deity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', related_query_name='building', to='settlements.Deity'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='required_settlement_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_type', related_query_name='building_type', to='settlements.Type'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement', related_query_name='settlement', to='territory.Territory'),
        ),
        migrations.AlterField(
            model_name='stronghold',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stronghold', related_query_name='stronghold', to='settlements.Building'),
        ),
        migrations.AlterField(
            model_name='stronghold',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stronghold', related_query_name='stronghold', to='territory.Territory'),
        ),
    ]
