# Generated by Django 2.0.5 on 2018-06-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0049_auto_20180607_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
