# Generated by Django 2.0.5 on 2018-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0050_lot_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
