# Generated by Django 2.0.5 on 2018-05-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0028_building_free_endowment'),
        ('territory', '0015_auto_20180529_1153'),
        ('festivals', '0002_auto_20180529_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='target_hex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='festival', related_query_name='festival', to='territory.Territory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festival',
            name='target_settlement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='festival', related_query_name='festival', to='settlements.Settlement'),
            preserve_default=False,
        ),
    ]
