# Generated by Django 2.0.5 on 2018-05-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_auto_20180529_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='target_hex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival', related_query_name='festival', to='territory.Territory'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='target_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival', related_query_name='festival', to='settlements.Settlement'),
        ),
    ]
