# Generated by Django 2.0.5 on 2018-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_auto_20180529_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
